A Bunch of small things to support this project!
BoogieMonster1O1/InnateMC pull request #2
Opened 2022-12-15 18:52 UTC by Jomyy

new instance in sheet and ui cleanups like add button as icon button and real searchbar for the instances, also download libs, assets and Minecraft jar on creation of new instance

2022-12-15 18:56 UTC, Jomyy commented
<img width="1012" alt="Bildschirm­foto 2022-12-15 um 19 54 39" src="https://user-images.githubusercontent.com/62953110/207943875-a691304f-339b-4eee-98d3-e9628579fbf0.png">
<img width="1012" alt="Bildschirm­foto 2022-12-15 um 19 55 39" src="https://user-images.githubusercontent.com/62953110/207944052-d9fd767b-093c-4bf6-933a-d46ea0d165d0.png">

2022-12-20 09:01 UTC, BoogieMonster1O1 requested changes

2022-12-20 09:01 UTC, BoogieMonster1O1 commented on InnateMC/ContentView.swift
> +        if #available(macOS 12.0, *) {
why does this need mac os 12? I run mac os 11 and `NavigationView` works with mac os 11

2022-12-20 09:01 UTC, BoogieMonster1O1 commented on InnateMC/Instance/InstanceLaunchView.swift
> +                    }catch{
```suggestion
                    } catch {
```

2022-12-20 09:01 UTC, BoogieMonster1O1 commented on InnateMC/Instance/InstanceLaunchView.swift
> +                    do{
```suggestion
                    do {
```

2022-12-20 15:38 UTC, Jomyy commented on InnateMC/ContentView.swift
> +        if #available(macOS 12.0, *) {
Oops left it in from when I was trying to use the . searchable thingy

2022-12-24 11:15 UTC, BoogieMonster1O1 commented on InnateMC/Instance/InstanceRuntimeView.swift
> +    @AppStorage("innatemc.maxMemory") private var maxMemory: Int = 1024
This is instance-specific, and shouldn't be stored with AppStorage

2022-12-24 11:24 UTC, merged